import { promises as fs } from "fs";
import path from "path";
import { Redis } from "@upstash/redis";
import type { ScanResponse } from "@/lib/scanner/types";

// Store for completed scan results, keyed by a short id and kept for 24 hours.
//
// Two backends, picked automatically:
//
//  1. Upstash Redis (used when UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN
//     are set). This is the one to use in production: Vercel and other serverless
//     hosts have a read-only, throwaway disk, so files can't hold share links.
//     Redis deletes each entry by itself after the 24-hour expiry.
//
//  2. Local disk (.shipornah-data/), used when those variables are missing. This is
//     only meant for `npm run dev` on your own machine.
//
// Callers (saveScanResult / getScanResult) are the same either way.

const TTL_SECONDS = 24 * 60 * 60; // 24 hours
const TTL_MS = TTL_SECONDS * 1000;

const STORE_DIR = path.join(process.cwd(), ".shipornah-data", "scans");
const LEGACY_STORE_DIR = path.join(process.cwd(), ".vibeguard-data", "scans");

const NOT_CONFIGURED_MESSAGE =
  "Scan storage isn't set up on this server. Set UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN.";

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function newId(): string {
  return crypto.randomUUID().replace(/-/g, "").slice(0, 12);
}

function isValidId(id: string): boolean {
  // Ids are generated by us (hex only). Check before using anything from a request
  // in a file path or a database key.
  return /^[a-f0-9]+$/i.test(id);
}

// ---------------------------------------------------------------------------
// Backend 1: Upstash Redis
// ---------------------------------------------------------------------------

let redisClient: Redis | null | undefined;

function getRedis(): Redis | null {
  if (redisClient !== undefined) return redisClient;

  // The KV_REST_API_* names are what Vercel's Upstash integration creates.
  const url = process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN;

  redisClient = url && token ? new Redis({ url, token }) : null;
  return redisClient;
}

const redisKey = (id: string) => `scan:${id}`;

async function getFromRedis(redis: Redis, id: string): Promise<ScanResponse | null> {
  try {
    const value = await redis.get<ScanResponse | string>(redisKey(id));
    if (!value) return null;
    return typeof value === "string" ? (JSON.parse(value) as ScanResponse) : value;
  } catch (err) {
    console.error("Could not read scan from Redis:", err);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Backend 2: local disk (development only)
// ---------------------------------------------------------------------------

function idToPath(id: string, storeDir = STORE_DIR): string {
  if (!isValidId(id)) throw new Error("Invalid scan id.");
  return path.join(storeDir, `${id}.json`);
}

async function saveToDisk(id: string, result: ScanResponse): Promise<void> {
  try {
    await fs.mkdir(STORE_DIR, { recursive: true });
    const entry = { result, createdAt: Date.now() };
    await fs.writeFile(idToPath(id), JSON.stringify(entry), "utf-8");
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    // Serverless hosts have a read-only disk. Say what's actually wrong.
    if (code === "EROFS" || code === "EACCES" || code === "EPERM") {
      throw new Error(NOT_CONFIGURED_MESSAGE);
    }
    throw err;
  }
}

async function getFromDisk(id: string): Promise<ScanResponse | null> {
  try {
    let filePath = idToPath(id);
    let raw: string;
    try {
      raw = await fs.readFile(filePath, "utf-8");
    } catch {
      filePath = idToPath(id, LEGACY_STORE_DIR);
      raw = await fs.readFile(filePath, "utf-8");
    }
    const entry = JSON.parse(raw) as { result: ScanResponse; createdAt: number };

    if (Date.now() - entry.createdAt > TTL_MS) {
      await fs.unlink(filePath).catch(() => {});
      return null;
    }

    return entry.result;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function saveScanResult(result: ScanResponse): Promise<string> {
  const id = newId();
  const redis = getRedis();

  if (redis) {
    await redis.set(redisKey(id), result, { ex: TTL_SECONDS });
  } else {
    await saveToDisk(id, result);
  }

  return id;
}

export async function getScanResult(id: string): Promise<ScanResponse | null> {
  if (!isValidId(id)) return null;

  const redis = getRedis();
  return redis ? getFromRedis(redis, id) : getFromDisk(id);
}
